import type { Plan } from "./types";

export const plans: Plan[] = [
  {
    id: "free",
    name: "Free",
    tagline: "Feel the product. Ship one live experience.",
    price_monthly_cents: 0,
    price_yearly_cents: 0,
    features: [
      "1 live experience",
      "Template library (read-only)",
      "Basic analytics (7 days)",
      "NeuroFunnel watermark",
    ],
    cta_label: "Start free",
    ios_product_id: "nf.free",
    stripe_price_id_monthly: "",
    stripe_price_id_yearly: "",
  },
  {
    id: "starter",
    name: "Starter",
    tagline: "For solo founders turning attention into revenue.",
    price_monthly_cents: 3900,
    price_yearly_cents: 39000,
    features: [
      "10 live experiences",
      "Full template library",
      "Full analytics (90 days)",
      "Remove watermark",
      "Email capture + exports",
    ],
    cta_label: "Upgrade to Starter",
    ios_product_id: "nf.starter.monthly",
    stripe_price_id_monthly: "price_starter_monthly",
    stripe_price_id_yearly: "price_starter_yearly",
  },
  {
    id: "pro",
    name: "Pro",
    tagline: "For operators compounding conversion week over week.",
    price_monthly_cents: 9900,
    price_yearly_cents: 99000,
    features: [
      "Unlimited experiences",
      "Perception Score insights",
      "Funnel drop-off AI diagnostics",
      "Custom domain + custom CSS",
      "Priority support",
    ],
    highlight: true,
    cta_label: "Upgrade to Pro",
    ios_product_id: "nf.pro.monthly",
    stripe_price_id_monthly: "price_pro_monthly",
    stripe_price_id_yearly: "price_pro_yearly",
  },
  {
    id: "agency",
    name: "Agency",
    tagline: "For teams building experiences for multiple brands.",
    price_monthly_cents: 29900,
    price_yearly_cents: 299000,
    features: [
      "5 workspaces",
      "Client billing pass-through",
      "Shared template libraries",
      "Role-based access",
      "Dedicated success partner",
    ],
    cta_label: "Talk to sales",
    ios_product_id: "nf.agency.monthly",
    stripe_price_id_monthly: "price_agency_monthly",
    stripe_price_id_yearly: "price_agency_yearly",
  },
];
